### ISSUE TITLE
Fabric API 0.20 breaks CBT

### ISSUE THREAD

**Issue by NeRdTheNed** [Nuclearfarts/connected-block-textures#18]
OS: Mac OS, but bug is likely OS agnostic. 
JVM: 8, 11, 14 (all 64 bit)
Loader version: 0.9.3+build.207
Game version: 1.16.2

Reproducible using just CBT 0.1.2 + Fabric API 0.20.0 build 399

Relevant bit from the log:

(normal log things)
[23:32:18] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
---- Minecraft Crash Report ----
// Sorry :(

Time: 5/09/20 11:32 PM
Description: Initializing game

java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218)
	at net.minecraft.class_3304.handler$zeo000$injectCBTPack(class_3304.java:1029)
	at net.minecraft.class_3304.method_18232(class_3304.java)
	at net.minecraft.class_310.<init>(class_310.java:569)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

Full log: [here](https://paste.ee/p/xIk2p)!

From a brief glance, CBT now seems to be trying to modify a ImmutableCollection, which is very :tiny_potato: in my books.

**Comment by NeRdTheNed** [comment]
(side note: this also happens with Fabric API 0.20.1 build 401!)

**Comment by hrmorley34** [comment]
Also with Fabric API 0.20.2 build 402 in 1.16.3 (on Windows 10)

**Comment by YTG1234** [comment]
@Nuclearfarts
